### ISSUE TITLE
Chapters with strange characters are excluded

### ISSUE THREAD

**Issue by MalcolmK** [mauvm/documark-table-of-contents#3]
Hey,

When I use a strange character in the name of my chapter (e.g. ë), it is not visible in the table of contents. Is this a bug in the plugin?

Malcolm Kindermans

**Comment by mauvm** [comment]
I just recently fixed this! So it should work in the latest version. `wkhtmltopdf` generates a `toc.xml` which I read with `ascii` encoding. I changed it to `UTF-8` which solves this problem.
